<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5bba400a04b6c',
    'title' => 'Skyfish Integration - Inställningar',
    'fields' => array(
        0 => array(
            'key' => 'field_5bba400d10454',
            'label' => __('Välj mapp', 'skyfish-integration'),
            'name' => 'skyfish_folder',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                424682 => 'Public',
                803040 => 'SFF',
                827312 => 'Public',
                1296342 => 'Trash',
                1297856 => 'Api',
                1354062 => 'Helsingborgs stad',
                1428498 => 'Samtycke',
                1539268 => 'Personal',
                1539324 => 'Ing-Marie Rundwall',
                1539327 => 'Maria Winberg-Nordström',
                1539328 => 'Övrig personal',
                1539778 => 'Tony Mufic',
                1539779 => 'Maria Holm',
                827167 => 'Manual',
                1326041 => 'Tina Carlström - kontaktcenter',
            ),
            'default_value' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
        1 => array(
            'key' => 'field_5bc723fbe4179',
            'label' => __('Sortera efter', 'skyfish-integration'),
            'name' => 'skyfish_order',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'created' => __('Publiceringsdatum', 'skyfish-integration'),
                'camera_created' => __('Kameradatum', 'skyfish-integration'),
                'relevance' => __('Relevans', 'skyfish-integration'),
            ),
            'default_value' => array(
                0 => 'created',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
        2 => array(
            'key' => 'field_5bc724eae417a',
            'label' => __('Sorteringsriktning', 'skyfish-integration'),
            'name' => 'skyfish_direction',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'desc' => __('Fallande', 'skyfish-integration'),
                'asc' => __('Stigande', 'skyfish-integration'),
            ),
            'default_value' => array(
                0 => 'desc',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
        3 => array(
            'key' => 'field_5bc7283ce417c',
            'label' => __('Sökläge', 'skyfish-integration'),
            'name' => 'skyfish_search_mode',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'default' => __('Standard', 'skyfish-integration'),
                'strict_and_search' => __('Strikt', 'skyfish-integration'),
                'wildcards' => __('Mjuk', 'skyfish-integration'),
            ),
            'default_value' => array(
                0 => 'default',
            ),
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
        4 => array(
            'key' => 'field_5d233c69d6aee',
            'label' => __('No connection fallback', 'skyfish-integration'),
            'name' => 'skyfish_no_connection_fallback',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-skyfish-gallery',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}